### ISSUE TITLE
A comparison to simov/slugify in the README would be very helpful

### ISSUE THREAD

**Issue by Soviut** [Trott/slug#318]
This project and https://github.com/simov/slugify are the first two results when you search either `npm slug` or `npm slugify`. I've been trying to compare the projects, but the features, the examples and the configuration all seem very similar. Both packages are updated regularly and you even contribute to both of them; which is awesome, but doesn't make it any easier to choose.

This is me right now.

![image](https://user-images.githubusercontent.com/226882/164609531-4c81fbe5-1926-41a4-ad44-7743d35703ad.png)

It would be great if there was a comparison in the README explaining any key differences to be aware of so anyone stumbling on both can tell them apart at a glance.

**Comment by Trott** [comment]
At this moment, the differences tend to be small and not things most users care much about.  For example:

* Slightly different defaults, notably that `slug` lowercases everything by default and `slugify` does not. So making a slug for `'On sale'` results in `'On-sale'` in `slugify` and `'on-sale'` in `slug`.
* This package still supports IE11 while `slugify` dropped IE11 some time ago. (However this package will be dropping IE11 support in June.)
* `slugify` changes currency designations (such as `$`) and other symbols to text by default while `slug` does not.  So `'$100'` becomes `'dollar100'` in `slugify` and `'100'` in `slug`. 
* `slug` will return a base64-ish string if it can't figure out what to do with any of the characters in a string. So for `'🎉'`, `slugify` returns an empty string (because the only characters in the string is something it doesn't have a map for) while `slug` returns `'8joiq'`.  The idea here is that returning a slug with no meaning is better than no slug at all. (If it appears in a string with other recognized characters, both `slug` and `slugify` will ignore the unrecognized character. In other words, both libraries will return `'party'` for `'🎉 party'`.)

There are other changes too but it's all small stuff and edge cases I think. (I have tests to make sure `slug` doesn't throw an error if it receives a lone surrogate but instead does the best it can with it. Not sure what `slugify` does, but that's also an edge case almost no user is going to face or care about. However, it suggests to me that if you are exposing the slugging library to a potentially hostile end user, you might want `slug` rather than `slugify`.)

A pull request adding this info to the README or in another doc would be welcome, but there are also much bigger changes coming in (hopefully) June. See the `beta` CHANGELOG at https://github.com/Trott/slug/blob/beta/CHANGELOG.md for what is planned so far.

**Comment by Trott** [comment]
Ping @simov in case they have comments they'd like to add.

**Comment by Soviut** [comment]
@Trott I'll see about making that pull request.

**Comment by simov** [comment]
> @simov Anything you'd add to this?

Thanks @Trott that's a pretty good summary. @Soviut we wanted to make sure we are not leaving anyone behind, so that's the reason why @Trott is helping over at `slugify` as well, but I'm assuming that `slug` is having a better support right now.

That being said either one should work for you so your call.

**Comment by Trott** [comment]
I guess I'll also add that `slugify` is likely stable for the foreseeable future without any planned big breaking API changes. (@simov Please correct me if I'm wrong about that!) As is probably clear from the beta changelog linked above, I'm planning a new release in June that will drop support for CommonJS and basically any module system other than ESM. So if you're all in on ESM, great, `slug` will probably be leaner and better for you. But if you want to keep using CommonJS or anything else that `slugify` supports, you may want to go with that.

**Comment by simov** [comment]
@Trott yes, that's a good point too.
