### ISSUE TITLE
migrate to something else now that karma is deprecated

### ISSUE THREAD

**Issue by Trott** [Trott/slug#440]

**Comment by screensaversclub** [comment]
Tried jest, pretty much drop in at this point. 

1. Installed `jest` 
2. Simple change for setup and teardown hooks: 

```diff
diff --git a/test/react-native.test.js b/test/react-native.test.js
index ccfb681..5a7c777 100644
--- a/test/react-native.test.js
+++ b/test/react-native.test.js
@@ -5,11 +5,11 @@ if (typeof window === 'undefined') {
   describe('React Native-like environment', function () {
     let slug

-    before(function () {
+    beforeEach(function () {
       global.window = {}
       delete require.cache[require.resolve('../slug')]
     })
-    after(function () {
+    afterEach(function () {
       delete global.window
       delete require.cache[require.resolve('../slug')]
     })
```

3. Running `jest` at this point produces the following: 

<img width="327" alt="image" src="https://github.com/Trott/slug/assets/67162738/380c8d78-34f3-4804-aed9-56b7faa8f3d8">

We could possibly migrate all `assert` functions to Jest's `expect` , which would allow us to remove a few devDependencies (https://jestjs.io/docs/migration-guide). 

Here's a WIP: 
https://github.com/Trott/slug/compare/main...screensaversclub:slug:jest-setup
(sorry about the formatting - I ran `npx standard --fix` so that the test would run. Will figure out how to preserve formatting if this refactor exercise looks like a go ahead)

**Comment by Trott** [comment]
If I'm not mistaken, that looks like you're using `jest` to replace `mocha`, which we don't need. We need browser testing.

**Comment by Trott** [comment]
I'm starting to wonder if the thing to do isn't just lose browser support. I (almost) never get bug reports and it seems likely that (almost) no one is using this on a web page (and people that are probably aren't going to update anyway).

**Comment by Trott** [comment]
Moved to web-test-runner.
