### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module y code: 'ERR_REQUIRE_ESM' 

### ISSUE THREAD

**Issue by MichaelDevCR** [Trott/slug#475]
Hello 

I am getting this error in the last version10.0.0, if I use slug 8.2.3, it works as respected

it looks like the syntaxis of import is not getting this library and is conflicting with the type of ESmodule

Code: 

```
import slug from 'slug';

export const name= async (req: Request, res: Response)=>{

const {email, password, handle} = req.body;// all are strings

console.log(slug(handle));

}
```

**Comment by Trott** [comment]
Can you please the entire stack trace for the error?

**Comment by Trott** [comment]
Based on the error message, something somewhere is using `require` to import `slug`, but slug@10 is ESM-only so that should no longer work. Your code above does not produce the error you are reporting for me in slug@10. So I'd like to see the stack trace because it seems like the error is coming from somewhere else.

**Comment by MichaelDevCR** [comment]
Hi
Another programmer fixed the issue, I just shared the information

the solution is the way to import

```
const { default: slug } = await import("slug");

console.log(slug(handle));
```
